In [4]:
import numpy as np

# Can create arrays with np.array
arr = np.array([1,2,3,4,5])
mixed_arr = np.array([1,2,3,4,'word'])

print('arr = ', arr)
print('.shape: ', arr.shape)
print('type(arr)', type(arr))
print('arr.dtype: ', arr.dtype)
print('arr.dtype: ', mixed_arr.dtype)

arr =  [1 2 3 4 5]
.shape:  (5,)
type(arr) <class 'numpy.ndarray'>
arr.dtype:  int64
arr.dtype:  <U21


In [7]:
# np.zeros fills an array with 0's
# np.ones does the same thing with 1's
# np.full(shape, value_to_fill_array_with)
zeros = np.zeros((3,3,2)) # Takes a tuple with the shape

print(zeros)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [8]:
# np.eye creates an Identity Matrix
eye = np.eye(5)
print(eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
# np.diag creates a Diagonal Matrix
diag = np.diag([1,2,3,4,5])
print(diag)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [10]:
# np.arange is another way to create arrays
# One argument will create an array with consecutive integers between 0 and n-1
a_arr = np.arange(5)
print(a_arr)

[0 1 2 3 4]


In [12]:
# Two arguments will create an array with consecutive integers between (start, stop)
a_arr2 = np.arange(5,10)
print(a_arr2)

[5 6 7 8 9]


In [13]:
# Three arguments - (start, stop, step)
step_arr = np.arange(10,50,5)
print(step_arr)

[10 15 20 25 30 35 40 45]


In [16]:
# You can use floats with arange, but it's best not to because of inconsistencies
# linspace handles floats better
# np.linspace(start, stop, N) where N is number of elements
# Notice both start and stop are INCLUDED unless endpoin=False is provided
lin = np.linspace(2, 4, 6)
print(lin)

[2.  2.4 2.8 3.2 3.6 4. ]


In [19]:
# np.reshape(ndarray, new_shape) takes an ndarray and reshapes it
old = np.arange(0,100,10)
print(old)
new_ndarr = np.reshape(old, (5,2))
print(new_ndarr)

[ 0 10 20 30 40 50 60 70 80 90]
[[ 0 10]
 [20 30]
 [40 50]
 [60 70]
 [80 90]]


In [24]:
# reshape is also available as a method
# reshape returns a new array, does not mutate in place
old = old.reshape(2,5)
print(old)

[[ 0 10 20 30 40]
 [50 60 70 80 90]]


In [25]:
# np.random.random(shape) creates and array with random floats
rando = np.random.random((3,3))
print(rando)

[[0.86460195 0.15905212 0.84527626]
 [0.59248021 0.98863172 0.90197604]
 [0.92827418 0.90010186 0.00373059]]


In [27]:
# np.random.randint(start, stop, size=shape) creates an array of random integers within start-stop
rand_int = np.random.randint(5, 10, size=(2,4))
print(rand_int)

[[5 7 9 8]
 [6 8 6 9]]


In [32]:
# np.random.normal(mean, std, size=shape) creates a normalized array
norm_arr = np.random.normal(0, 0.1, size=(1000,1000))

print('mean: ', norm_arr.mean())
print('max: ', norm_arr.max())
print('min: ', norm_arr.min())

# ndarrays have some very interesting behavior
print('norm_arr has', (norm_arr < 0).sum(), 'negative numbers')
print('norm_arr has', (norm_arr > 0).sum(), 'positive numbers')
print('Item in first row, second column: ', norm_arr[0,2])

mean:  0.00013536482184152093
max:  0.48140874069264233
min:  -0.5150386689310283
norm_arr has 499637 negative numbers
norm_arr has 500363 positive numbers
Item in first row, second column:  0.05543820637794336


In [33]:
spliced = norm_arr[1:10,2:5]
print(spliced)

[[ 0.15282166 -0.14771218 -0.02333298]
 [ 0.00659051 -0.12186279  0.00201664]
 [ 0.06835678  0.11073126  0.06773756]
 [-0.19476285  0.07941041 -0.19091989]
 [ 0.07064285 -0.02857085 -0.10440298]
 [ 0.10982631 -0.19318936 -0.0848595 ]
 [ 0.25505343  0.06985588  0.03688258]
 [-0.07333128  0.0895035   0.20959903]
 [ 0.04441284 -0.01928323  0.10060501]]


In [35]:
arr = np.array([[1,2,3],[1,1,1],[2,2,2]])
unique_arr = np.unique(arr)
print(unique_arr)

[1 2 3]


In [36]:
#  Boolean indexing
arr = np.arange(25).reshape(5, 5)
print('Greater than 10: ', arr[arr > 10])
print('Less than or equal to 8: ', arr[arr <= 8])
print('Between 10 and 17:', arr[(arr > 10) & (arr < 17)])

Greater than 10:  [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Less than or equal to 8:  [0 1 2 3 4 5 6 7 8]
Between 10 and 17: [11 12 13 14 15 16]


In [42]:
# np.sort(ndarray, axis=) sorts out of place
# ndarray.sort(axis=, kind=(takes a sorting algo), order=(str or list of str)) sorts in place
rando = np.random.randint(1,11,size=(5,5))
print('Sorted\n', np.sort(rando))

print('\nOriginal\n', rando)

rando.sort(axis=0)
print('\nSorted on columns\n', rando)

Sorted
 [[ 2  2  7  7 10]
 [ 2  4  5  7 10]
 [ 1  2  4  5  9]
 [ 3  5  5  6  9]
 [ 3  3  3  7  8]]

Original
 [[ 7  7  2 10  2]
 [ 2  5  4 10  7]
 [ 2  4  1  5  9]
 [ 3  5  6  9  5]
 [ 8  3  7  3  3]]

Sorted on columns
 [[ 2  3  1  3  2]
 [ 2  4  2  5  3]
 [ 3  5  4  9  5]
 [ 7  5  6 10  7]
 [ 8  7  7 10  9]]
